### PR TITLE
Upgrade to Dokan 2.2.0 and bump dependencies

### PR DESCRIPTION
**Pull request by denisovpi**
- Upgrade to **Dokan 2.2.0**.
- Bump dependencies.

### CODE REVIEW

**Comment by Liryna** [comment]
Hi @denisovpi ,

Thank you for the pull request! Do you have any idea why it would be crashing on the CI ?
https://ci.appveyor.com/project/Liryna/dokan-rust/builds/50870798/job/i260528asart3lq2

**Comment by denisovpi** [comment]
Hi @Liryna, thank you for such a great project!

My understanding is that this was because the maximum allowable build time was reached (there's a message - "Build execution time has reached the maximum allowed time for your plan (60 minutes)."), but why it took so long it's hard to say. Maybe there was a problem on the server.

The third test (Environment: ARCH=i686, TOOLCHAIN=msvc) failed because it did not pass this test - **usage_tests::can_find_files**.
The following condition is not met
https://github.com/dokan-dev/dokan-rust/blob/f3c22801c87047d3f38a55c3ec936353e4587b9e/dokan/src/usage_tests.rs#L1143
I don't have enough experience with Dokan yet for me to be able to correct this test, but I noticed that this test didn't pass in previous build either.

It would be nice if @KoltesDigital could help with that.

**Comment by Liryna** [comment]
Thanks @denisovpi !

> The third test (Environment: ARCH=i686, TOOLCHAIN=msvc) failed because it did not pass this test - usage_tests::can_find_files.
The following condition is not met

Those two (`..` and `.`) are now found first from dokany 2.1.0 so those lines can be moved at `1193` with `.` first and `..` second.
https://github.com/dokan-dev/dokan-rust/blob/f3c22801c87047d3f38a55c3ec936353e4587b9e/dokan/src/usage_tests.rs#L1171-L1180

Could you also try to add [DokanRegisterWaitForFileSystemClosed & DokanUnregisterWaitForFileSystemClosed](https://github.com/dokan-dev/dokany/blob/45021e00ec54e38b936620f339c8fb22c3f999d2/dokan/dokan.h#L896-L909) somewhere [here](https://github.com/dokan-dev/dokan-rust/blob/f3c22801c87047d3f38a55c3ec936353e4587b9e/dokan-sys/src/lib.rs#L325) ? They were also added in 2.1.0

**Comment by denisovpi** [comment]
I added 'DokanRegisterWaitForFileSystemClosed' and 'DokanUnregisterWaitForFileSystemClosed' functions but they are not used in the code.

**Comment by Liryna** [comment]
Thanks @denisovpi ! The CI still seems to hang or crash for some reason.
Will probably try to add this to the appveyor config and see whether it is a BSOD
https://github.com/dokan-dev/dokany/blob/master/appveyor.yml#L311-L353

As my rust knowledge are limited, I will give @KoltesDigital a few more days to look into it before merging.

**Comment by denisovpi** [comment]
I decided to run tests on AppVeyor separately to see what the problem is. But I couldn't do that because the service has been unstable lately.
https://help.appveyor.com/discussions/problems/37347-there-was-an-error-while-trying-to-complete-the-current-operation-please-contact-appveyor-support
https://help.appveyor.com/discussions/problems/37329-error
https://help.appveyor.com/discussions/problems/36699-project-stopped-building-from-github

I don't think the issue is with our code. If I run locally, all tests succeed except 'can_get_operation_info'. I'm going to try to fix that too.

**Comment by denisovpi** [comment]
I fixed the tests. If a single thread is used, all tests pass.

**Comment by Liryna** [comment]
@denisovpi Sorry for the delay! Thanks again for your contribution and fixing the tests 🏆 . If you have other ideas of changes for the wrapper let me know. I will ensure the review is quicker next time

**Pull request merged**
